import { Injectable } from '@angular/core';
import { Personaje } from '../models/personaje.model';

@Injectable({
  providedIn: 'root',
})
export class PersonajesService {
  private personajes: Personaje[] = [
    // Heroes Marvel //
    {
      nombre: 'Spider-Man',
      alias: 'Peter Parker',
      imagen: 'assets/personajes/spiderman.jpg',
      descripcion: 'Un joven con habilidades arácnidas que lucha contra el crimen en Nueva York.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Iron Man',
      alias: 'Tony Stark',
      imagen: 'assets/personajes/ironman.jpg',
      descripcion: 'Un genio multimillonario que utiliza una armadura avanzada para combatir el mal.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Thor',
      alias: 'Thor Odinson',
      imagen: 'assets/personajes/thor.jpg',
      descripcion: 'El dios del trueno de Asgard, que protege la Tierra con su poderoso martillo Mjolnir.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Captain America',
      alias: 'Steve Rogers',
      imagen: 'assets/personajes/captainamerica.jpg',
      descripcion: 'Un super soldado que lucha por la justicia y la libertad durante la Segunda Guerra Mundial.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Hulk',
      alias: 'Bruce Banner',
      imagen: 'assets/personajes/hulk.jpg',
      descripcion: 'Un científico que se transforma en un gigante verde y poderoso cuando se enfurece.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Black Widow',
      alias: 'Natasha Romanoff',
      imagen: 'assets/personajes/blackwidow.jpg',
      descripcion: 'Una espía y experta en artes marciales que trabaja para S.H.I.E.L.D.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Hawkeye',
      alias: 'Clint Barton',
      imagen: 'assets/personajes/hawkeye.jpg',
      descripcion: 'Un arquero excepcionalmente hábil y miembro de los Vengadores.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Doctor Strange',
      alias: 'Stephen Strange',
      imagen: 'assets/personajes/doctorstrange.jpg',
      descripcion: 'Un ex neurocirujano que se convierte en el Hechicero Supremo, protegiendo la Tierra de amenazas místicas.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Black Panther',
      alias: 'T\'Challa',
      imagen: 'assets/personajes/blackpanther.jpg',
      descripcion: 'El rey de Wakanda, que posee habilidades sobrehumanas gracias a la hierba en forma de corazón.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Captain Marvel',
      alias: 'Carol Danvers',
      imagen: 'assets/personajes/captainmarvel.jpg',
      descripcion: 'Una piloto de la Fuerza Aérea que adquiere poderes cósmicos y se convierte en una heroína intergaláctica.',
      afiliacion: 'Heroe',
      universo: 'Marvel',
    },

    // AntiHeroes Marvel //
    {
      nombre: 'Deadpool',
      alias: 'Wade Wilson',
      imagen: 'assets/personajes/deadpool.jpg',
      descripcion: 'Un mercenario con habilidades regenerativas y un sentido del humor irreverente.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Wolverine',
      alias: 'Logan',
      imagen: 'assets/personajes/wolverine.jpg',
      descripcion: 'Un mutante con garras retráctiles y un factor de curación acelerado.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Venom',
      alias: 'Eddie Brock',
      imagen: 'assets/personajes/venom.jpg',
      descripcion: 'Un simbionte alienígena que se une a Eddie Brock, otorgándole poderes sobrehumanos.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Punisher',
      alias: 'Frank Castle',
      imagen: 'assets/personajes/punisher.jpg',
      descripcion: 'Un vigilante que lucha contra el crimen utilizando métodos letales.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Elektra',
      alias: 'Elektra Natchios',
      imagen: 'assets/personajes/elektra.jpg',
      descripcion: 'Una asesina entrenada en artes marciales que a veces actúa como aliada de Daredevil.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Moon Knight',
      alias: 'Marc Spector',
      imagen: 'assets/personajes/moonknight.jpg',
      descripcion: 'Un ex mercenario que se convierte en un vigilante con múltiples personalidades.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Winter Soldier',
      alias: 'Bucky Barnes',
      imagen: 'assets/personajes/wintersoldier.jpg',
      descripcion: 'Un soldado mejorado con habilidades sobrehumanas y un brazo biónico.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Scarlet Witch',
      alias: 'Wanda Maximoff',
      imagen: 'assets/personajes/scarletwitch.jpg',
      descripcion: 'Una mutante con habilidades de manipulación de la realidad y la magia.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Quicksilver',
      alias: 'Pietro Maximoff',
      imagen: 'assets/personajes/quicksilver.jpg',
      descripcion: 'Un mutante con la capacidad de moverse a velocidades sobrehumanas.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },
    {
      nombre: 'Silver Surfer',
      alias: 'Norrin Radd',
      imagen: 'assets/personajes/silversurfer.jpg',
      descripcion: 'Un heraldo cósmico con la capacidad de manipular la energía y viajar a través del espacio.',
      afiliacion: 'AntiHeroe',
      universo: 'Marvel',
    },

    // Villanos Marvel //
    {
      nombre: 'Loki',
      alias: 'Loki Laufeyson',
      imagen: 'assets/personajes/loki.jpg',
      descripcion: 'El dios de las mentiras y el engaño, hermano adoptivo de Thor.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Thanos',
      alias: 'Thanos',
      imagen: 'assets/personajes/thanos.jpg',
      descripcion: 'Un titán loco obsesionado con el equilibrio universal, conocido por reunir las Gemas del Infinito.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Green Goblin',
      alias: 'Norman Osborn',
      imagen: 'assets/personajes/greengoblin.jpg',
      descripcion: 'Un empresario loco y archienemigo de Spider-Man.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Doctor Octopus',
      alias: 'Otto Octavius',
      imagen: 'assets/personajes/doctoroctopus.jpg',
      descripcion: 'Un científico con brazos mecánicos que se convierte en un enemigo de Spider -Man.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Magneto',
      alias: 'Erik Lehnsherr',
      imagen: 'assets/personajes/magneto.jpg',
      descripcion: 'Un mutante con la capacidad de controlar el magnetismo y líder de los Hermanos Mutantes.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Red Skull',
      alias: 'Johann Schmidt',
      imagen: 'assets/personajes/redskull.jpg',
      descripcion: 'Un líder nazi y archienemigo del Capitán América.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Ultron',
      alias: 'Ultron',
      imagen: 'assets/personajes/ultron.jpg',
      descripcion: 'Una inteligencia artificial malvada creada por Tony Stark que busca la destrucción de la humanidad.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Kingpin',
      alias: 'Wilson Fisk',
      imagen: 'assets/personajes/kingpin.jpg',
      descripcion: 'Un poderoso criminal y archienemigo de Daredevil.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },
    {
      nombre: 'Mistério',
      alias: 'Quentin Beck',
      imagen: 'assets/personajes/misterio.jpg',
      descripcion: 'Un maestro de las ilusiones y enemigo de Spider-Man.',
      afiliacion: 'Villano',
      universo: 'Marvel',
    },

    // Heroes DC //
    {
      nombre: 'Superman',
      alias: 'Clark Kent',
      imagen: 'assets/personajes/superman.jpg',
      descripcion: 'Un extraterrestre del planeta Krypton con superpoderes que protege la Tierra.',
      afiliacion: 'Heroe',
      universo: 'DC',
    },
    {
      nombre: 'Batman',
      alias: 'Bruce Wayne',
      imagen: 'assets/personajes/batman.jpg',
      descripcion: 'Un vigilante enmascarado que lucha contra el crimen en Gotham City.',
      afiliacion: 'Heroe',
      universo: 'DC',
    },
    {
      nombre: 'Wonder Woman',
      alias: 'Diana Prince',
      imagen: 'assets/personajes/wonderwoman.jpg',
      descripcion: 'Una princesa amazona con fuerza sobrehumana y habilidades de combate excepcionales.',
      afiliacion: 'Heroe',
      universo: 'DC',
    },
    {
      nombre: 'The Flash',
      alias: 'Barry Allen',
      imagen: 'assets/personajes/flash.jpg',
      descripcion: 'Un velocista con la capacidad de moverse a velocidades increíbles.',
      afiliacion: 'Heroe',
      universo: 'DC',
    },
    {
      nombre: 'Aquaman',
      alias: 'Arthur Curry',
      imagen: 'assets/personajes/aquaman.jpg',
      descripcion: 'El rey de Atlantis con la capacidad de comunicarse con la vida marina.',
      afiliacion: 'Heroe',
      universo: 'DC',
    },
    {
      nombre: 'Green Lantern',
      alias: 'Hal Jordan',
      imagen: 'assets/personajes/greenlantern.jpg',
      descripcion: 'Un miembro del Cuerpo de Green Lanterns que utiliza un anillo de poder para crear construcciones de energía verde.',
      afiliacion: 'Heroe',
      universo: 'DC',
    },
    {
      nombre: 'Shazam',
      alias: 'Billy Batson',
      imagen: 'assets/personajes/shazam.jpg',
      descripcion: 'Un joven que se transforma en un superhéroe adulto con poderes mágicos al pronunciar la palabra "Shazam".',
      afiliacion: 'Heroe',
      universo: 'DC',
    },
    {
      nombre: 'Green Arrow',
      alias: 'Oliver Queen',
      imagen: 'assets/personajes/greenarrow.jpg',
      descripcion: 'Un arquero experto y vigilante que lucha contra el crimen en Star City.',
      afiliacion: 'Heroe',
      universo: 'DC',
    },

    // Villanos DC //
    {
      nombre: 'Joker',
      alias: 'Desconocido',
      imagen: 'assets/personajes/joker.jpg',
      descripcion: 'Un criminal psicópata y archienemigo de Batman.',
      afiliacion: 'Villano',
      universo: 'DC',
    },
    {
      nombre: 'Darkseid',
      alias: 'Darkseid',
      imagen: 'assets/personajes/darkseid.jpg',
      descripcion: 'Un dios tirano de Apokolips que busca conquistar el universo.',
      afiliacion: 'Villano', 
      universo: 'DC',
    },
    {
      nombre: 'Harley Quinn',
      alias: 'Harleen Quinzel',
      imagen: 'assets/personajes/harleyquinn.jpg',
      descripcion: 'Una ex psiquiatra que se convierte en la compañera del Joker y una villana caótica.',
      afiliacion: 'Villano',
      universo: 'DC',
    },
    {
      nombre: 'Deathstroke',
      alias: 'Slade Wilson',
      imagen: 'assets/personajes/deathstroke.jpg',
      descripcion: 'Un mercenario y asesino experto con habilidades sobrehumanas.',
      afiliacion: 'Villano',
      universo: 'DC',
    },
    {
      nombre: 'Brainiac',
      alias: 'Brainiac',
      imagen: 'assets/personajes/brainiac.jpg',
      descripcion: 'Una inteligencia artificial alienígena que busca adquirir conocimiento y destruir mundos.',
      afiliacion: 'Villano',
      universo: 'DC',
    },
    {
      nombre: 'Sinestro',
      alias: 'Thaal Sinestro',
      imagen: 'assets/personajes/sinestro.jpg',
      descripcion: 'Un ex Green Lantern que se convierte en un villano y líder del Cuerpo de Sinestro.',
      afiliacion: 'Villano',
      universo: 'DC',
    },
    {
      nombre: 'Black Manta',
      alias: 'David Hyde',
      imagen: 'assets/personajes/blackmanta.jpg',
      descripcion: 'Un enemigo de Aquaman con un traje avanzado que le permite respirar bajo el agua y luchar contra el héroe.',
      afiliacion: 'Villano',
      universo: 'DC',
    },
    {
      nombre: 'Two-Face',
      alias: 'Harvey Dent',
      imagen: 'assets/personajes/twoface.jpg',
      descripcion: 'Un ex fiscal de distrito que se convierte en un villano con una personalidad dividida.',
      afiliacion: 'Villano',
      universo: 'DC',
    },
  ];

  constructor() {}

  getPersonajes(): Personaje[] {
    return this.personajes;
  }

  searchPersonajesByName(name: string): Personaje[] {
    return this.personajes.filter((personaje) =>
      personaje.nombre.toLowerCase().includes(name.toLowerCase()) ||
      personaje.alias.toLowerCase().includes(name.toLowerCase())
    );
  }
}
